#! /bin/sh

bspc config border_width        8
bspc config window_gap          20

bspc config split_ratio         0.56
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d 1 2 3 4
#bspc monitor HDMI1 -d 9

#bspc rule -a Chromium desktop=^5

nitrogen --restore
polybar top &
compton &
