#! /bin/sh

bspc config border_width        6
bspc config window_gap          24

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d $(echo -e '\uf109') $(echo -e '\uf121') $(echo -e '\uf120') $(echo -e '\uf07c') $(echo -e '\uf0ac') $(echo -e '\uf0c3')  $(echo -e '\uf141') $(echo -e '\uf001')

bspc rule -a Chromium desktop=^5

nitrogen --restore
panel &
#compton -c &
