#! /bin/sh

bspc config -m eDP1 top_padding 10
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 0
bspc config window_gap 80

bspc config split_ratio 0.56
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true

bspc config pointer_follows_focus true
bspc config click_to_focus true

#bspc config active_border_color "#1aff8c"
#bspc config focused_border_color "#ccffe6"
#bspc config normal_border_color "#001a0d"

bspc monitor eDP1 -d 1 2 3 4 5

bspc monitor HDMI1 -d 6

#bspc rule -a Chromium desktop=^5
bspc rule -a Gimp state=floating

nitrogen --restore
polybar top &
compton &
redshift &
conky &
