#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=48
PANEL_FONT_FAMILY="Inconsolata-12:Regular"
ICON_FONT="FontAwesome:size=12"

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &

# clock
while true;
	do
		echo -e 'C\uf017' $(date +"%l:%M %p");
	sleep 30;
done > "$PANEL_FIFO" &

# date
while true;
do echo -e 'D\uf073' $(date +'%b %d')
	sleep 10
done > $PANEL_FIFO &
# battery
while true;
do
BATT_LEVEL=$(acpi -b | grep -o '[[:digit:]]\+%' | sed 's/%//')
	if [ $BATT_LEVEL -ge 97 ]
		then
			echo -e 'B\uf240' $BATT_LEVEL%
	fi

	if [ $BATT_LEVEL -ge 63 -a $BATT_LEVEL -lt 97 ]
		then
			echo -e 'B\uf241' $BATT_LEVEL%
	fi

	if [ $BATT_LEVEL -ge 36 -a $BATT_LEVEL -lt 63 ]
		then
			echo -e 'B\uf242' $BATT_LEVEL%
	fi

	if [ $BATT_LEVEL -lt 30 ]
		then
			echo -e 'B%{T3}\uf243%{T1}' $BATT_LEVEL%
	fi


	sleep 40;
done > "$PANEL_FIFO" &

# alsa volume
while true;
do
ALSA_VOLUME=$(amixer get Master | grep 'Mono: Playback' | grep -o '...%' | sed 's/\[//' | sed 's/%//' | sed 's/ //')
ALSA_STATE=$(amixer get Master | grep 'Mono: Playback' | grep -o '\[on]')

if [ $ALSA_STATE ]
then
	if [ $ALSA_VOLUME -ge 50 ]
	then
		echo -e V'\uf028' $ALSA_VOLUME
	fi
	if [ $ALSA_VOLUME -gt 0 -a $ALSA_VOLUME -lt 50 ]
	then
		echo -e V'\uf027' $ALSA_VOLUME
	fi
	if [ $ALSA_VOLUME -eq 0 ]
	then
		echo -e V'\uf026' $ALSA_VOLUME
	fi
	else
		echo -e V'\uf026' $ALSA_VOLUME
	fi
	sleep 10
done > $PANEL_FIFO &


# wifi
while true;
do
WIFI_SSID=$(iw wlan0 link | grep 'SSID' | sed 's/SSID: //' | sed 's/\t//')
WIFI_SIGNAL=$(iw wlan0 link | grep 'signal' | sed 's/signal: //' | sed 's/ dBm//' | sed 's/\t//')
	echo -e L'\uf1eb' $WIFI_SSID '|' $WIFI_SIGNAL
	sleep 30
done > $PANEL_FIFO &

# power
echo -e P'\uf011' > $PANEL_FIFO &
. panel_colors

cat "$PANEL_FIFO" | panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -f "$ICON_FONT" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait
